name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    container: texlive/texlive:latest
    env:
      CV_FILENAME: Sam_Hartley_Senior_Software_Engineer_CV.pdf
    steps:
      - uses: actions/checkout@v4

      - name: Install Node.js
        run: |
          apt-get update -qq
          apt-get install -y curl
          curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
          apt-get install -y nodejs

      - name: Build PDF
        run: pdflatex -jobname="${CV_FILENAME%.pdf}" cv.tex

      - name: Install wrangler
        run: npm install -g wrangler

      - name: Deploy to Cloudflare R2
        run: |
          wrangler r2 object put ${{ secrets.R2_BUCKET_NAME }}/$CV_FILENAME --file=$CV_FILENAME --remote
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CV_FILENAME: Sam_Hartley_Senior_Software_Engineer_CV.pdf

      - name: Purge Cloudflare cache
        run: |
          curl https://api.cloudflare.com/client/v4/zones/$CLOUDFLARE_ZONE_ID/purge_cache \
            -H 'Content-Type: application/json' \
            -H "Authorization: Bearer $CLOUDFLARE_CACHE_PURGE_API_TOKEN" \
            -d '{
                  "hosts": [
                    "cv.jamtartley.com"
                  ]
                }'
        env:
          CLOUDFLARE_CACHE_PURGE_API_TOKEN: ${{ secrets.CLOUDFLARE_CACHE_PURGE_API_TOKEN }}
          CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
